# Generated by Django 5.1.6 on 2025-03-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_blogpost_likes_like_created_at_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
